[project]
name = "assignments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "pandas>=2.3.2",
    "pymupdf>=1.26.4",
    "pyspark-stubs>=3.0.0.post3",
    "requests>=2.32.5",
    "w3lib>=2.3.1",
]
