[project]
name = "assignments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.2",
    "pymupdf>=1.26.4",
    "requests>=2.32.5",
]
